services:
    v12mike.symbols.listener:
        class: v12mike\symbols\event\listener
        arguments:
            - '@template'
            - ext/v12mike/symbols/
        tags:
            - { name: event.listener }
